language: python
sudo: false

python:
  - "2.7"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
    - python-tk

install:
  - pip install tox
  - pip install coveralls

script:
  pytest -vv -s --cov=conport --cov-report term --cov-report html

after_success:
  coveralls
